version: '3'

services:
  mysql:
    container_name: littlelemon
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d